name: Data Processing Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day. Modify as needed.

jobs:
  update-and-train:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set the Python version as per your project's need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/test_requirements.txt  # Assumes you have a requirements.txt at your repo's root

    - name: Update Data
      run: python src/pipeline/update_with_latest_data.py

    - name: Prepare Data for Training
      run: python src/pipeline/prepare_latest_data_for_training.py

    - name: Run Training
      run: python src/pipeline/train.py

    # Add additional steps if needed, like pushing changes to the repository
